export const IPC_CHANNELS = {
  tabs: {
    getTab: 'kernel:tabs:getTab',
    getAllTabs: 'kernel:tabs:getAllTabs',
    getTabsByWorkspace: 'kernel:tabs:getTabsByWorkspace',
    getActiveTab: 'kernel:tabs:getActiveTab',
    createTab: 'kernel:tabs:createTab',
    closeTab: 'kernel:tabs:closeTab',
    closeTabs: 'kernel:tabs:closeTabs',
    activateTab: 'kernel:tabs:activateTab',
    navigateTo: 'kernel:tabs:navigateTo',
    goBack: 'kernel:tabs:goBack',
    goForward: 'kernel:tabs:goForward',
    reload: 'kernel:tabs:reload',
    stop: 'kernel:tabs:stop',
    duplicateTab: 'kernel:tabs:duplicateTab',
    pinTab: 'kernel:tabs:pinTab',
    unpinTab: 'kernel:tabs:unpinTab',
    muteTab: 'kernel:tabs:muteTab',
    unmuteTab: 'kernel:tabs:unmuteTab',
    moveTab: 'kernel:tabs:moveTab',
    moveTabToWorkspace: 'kernel:tabs:moveTabToWorkspace',
    setZoom: 'kernel:tabs:setZoom',
    findInPage: 'kernel:tabs:findInPage',
    stopFindInPage: 'kernel:tabs:stopFindInPage',
    // Events (main -> renderer)
    onTabCreated: 'kernel:tabs:onTabCreated',
    onTabClosed: 'kernel:tabs:onTabClosed',
    onTabUpdated: 'kernel:tabs:onTabUpdated',
    onTabActivated: 'kernel:tabs:onTabActivated',
    onTabMoved: 'kernel:tabs:onTabMoved',
  },
  workspaces: {
    getWorkspace: 'kernel:workspaces:getWorkspace',
    getAllWorkspaces: 'kernel:workspaces:getAllWorkspaces',
    getActiveWorkspace: 'kernel:workspaces:getActiveWorkspace',
    createWorkspace: 'kernel:workspaces:createWorkspace',
    deleteWorkspace: 'kernel:workspaces:deleteWorkspace',
    renameWorkspace: 'kernel:workspaces:renameWorkspace',
    updateWorkspace: 'kernel:workspaces:updateWorkspace',
    activateWorkspace: 'kernel:workspaces:activateWorkspace',
    reorderWorkspace: 'kernel:workspaces:reorderWorkspace',
    onWorkspaceCreated: 'kernel:workspaces:onWorkspaceCreated',
    onWorkspaceDeleted: 'kernel:workspaces:onWorkspaceDeleted',
    onWorkspaceUpdated: 'kernel:workspaces:onWorkspaceUpdated',
    onWorkspaceActivated: 'kernel:workspaces:onWorkspaceActivated',
  },
  navigation: {
    resolveInput: 'kernel:navigation:resolveInput',
    getSuggestions: 'kernel:navigation:getSuggestions',
    getSecurityInfo: 'kernel:navigation:getSecurityInfo',
  },
  window: {
    setContentBounds: 'kernel:window:setContentBounds',
    setSidebarWidth: 'kernel:window:setSidebarWidth',
    toggleSidebar: 'kernel:window:toggleSidebar',
    onBoundsChanged: 'kernel:window:onBoundsChanged',
  },
} as const;
