packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  canvas: false
  electron: false
  electron-winstaller: false
  es5-ext: false
  esbuild: true
  lefthook: true
  nx: true
  protobufjs: true
  sharp: false
